name: Build APK from Compressed File
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install p7zip
        run: sudo apt-get install p7zip-full -y
        
      - name: Extract Project
        run: 7z x aura-vpn.7z
        
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - run: npm install
      
      - name: Build with Gradle
        run: |
          find . -name "gradlew" -exec chmod +x {} \;
          GRADLE_PATH=$(find . -name "gradlew" | head -n 1)
          cd $(dirname $GRADLE_PATH) && ./gradlew assembleDebug
      
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: "**/*.apk"
